version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      pihole_network:
        ipv4_address: '192.168.8.222' #update, assign open ip manually
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Dublin' # update according to your timezone
      WEBPASSWORD: 'calstPi' #update password
    volumes:
      - '/home/calst/pihole/etc-pihole:/etc/pihole' #update
      - '/home/calst/pihole/etc-dnsmasq.d:/etc/dnsmasq.d' #update
    cap_add:
      - NET_ADMIN
    restart: unless-stopped


networks:
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.8.0/24 #update if needed
          gateway: 192.168.8.1 #update if needed
